[Rainmeter]
Update=-1

[Variables]
Scale=0.6
; Default is White (ffffffff)
IconTint=ffffffff

[MeterImage]
Meter=Image
ImageName=#@#cod\Original.png      
W=(200*#Scale#)
ImageTint=#IconTint#
PreserveAspectRatio=1
DynamicVariables=1
SolidColor=0,0,0,1
LeftMouseUpAction=[!SetOption #CURRENTSECTION# ImageName "#@#cod\ClickedImage.png"][!UpdateMeter #CURRENTSECTION#][!Redraw]["E:\Games\call of duty ghosts original\Call of Duty Ghosts\iw6-mod.exe"]
MouseScrollDownAction=[!WriteKeyValue Variables Scale (#Scale#+0.1)][!SetVariable Scale (#Scale#+0.1)][!UpdateMeter MeterImage][!Redraw]
MouseScrollUpAction=[!WriteKeyValue Variables Scale (#Scale#-0.1)][!SetVariable Scale (#Scale#-0.1)][!UpdateMeter MeterImage][!Redraw]
 
; --- THE SWAP LOGIC ---
; When hovering, change ImageName to the "Hover" version
MouseOverAction=[!SetOption #CURRENTSECTION# ImageName "#@#cod\HoverImage.png"][!UpdateMeter #CURRENTSECTION#][!Redraw]

; When leaving, change ImageName back to the "Original" version
MouseLeaveAction=[!SetOption #CURRENTSECTION# ImageName "#@#cod\Original.png"][!UpdateMeter #CURRENTSECTION#][!Redraw]

